"""Validate and coerce the raw OpenAI JSON into TreatmentResponse."""

from __future__ import annotations

import json
import logging

from models.schemas import TreatmentResponse

logger = logging.getLogger(__name__)

_DEFAULT_DISCLAIMER = (
    "[AI-GENERATED - NOT A SUBSTITUTE FOR PROFESSIONAL CLINICAL JUDGMENT] "
    "This output is generated by an AI clinical decision-support tool. "
    "It is NOT a diagnosis and does NOT replace the professional judgment "
    "of a qualified prosthodontist or dentist. Always verify findings clinically "
    "before making treatment decisions."
)


def validate_response(raw_json: str) -> TreatmentResponse:
    """Parse *raw_json* into a validated TreatmentResponse.

    Applies safe defaults for any missing fields and ensures the
    disclaimer is always present.
    """
    try:
        data = json.loads(raw_json)
    except json.JSONDecodeError as exc:
        logger.error("OpenAI returned invalid JSON: %s", exc)
        return _fallback_response(str(exc))

    if not isinstance(data, dict):
        logger.error("OpenAI returned non-object JSON")
        return _fallback_response("Response was not a JSON object.")

    # Ensure disclaimer exists
    if not data.get("disclaimer"):
        data["disclaimer"] = _DEFAULT_DISCLAIMER

    try:
        return TreatmentResponse.model_validate(data)
    except Exception as exc:
        logger.error("Validation failed: %s", exc)
        return _fallback_response(str(exc))


def _fallback_response(error_detail: str) -> TreatmentResponse:
    """Return a safe fallback response when parsing/validation fails."""
    return TreatmentResponse(
        case_summary="The AI was unable to produce a fully structured response for this case.",
        need_more_information=["Please re-submit the case. If the issue persists, simplify the input."],
        red_flags=[],
        confidence_level="low",
        disclaimer=_DEFAULT_DISCLAIMER,
    )
